import localFont from "next/font/local";
import "./globals.css";
import AOSInit from "@/app/lib/utils/Aos";
import ScrollToTop from "@/app/lib/utils/ScrollToTop";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "شرکت ست کافی - Set Coffee",
  description: "Generated by create next app",
  icons: {
    icon: "https://cdn-icons-png.flaticon.com/512/8230/8230211.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AOSInit />
        <ScrollToTop />
        {children}
      </body>
    </html>
  );
}
